"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "EN" | "FR";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    // Nav
    "nav-home": "Home",
    "nav-about": "About",
    "nav-about-event": "About THE Event",
    "nav-team": "THE Team",
    "nav-travel": "Travel & Accommodations",
    "nav-media": "Recent Media",
    "nav-newsflash": "THE Newsflash",
    "nav-programs": "Programs",
    "nav-student": "The Student Sponsorship Program",
    "nav-sheco": "SHE-Co Initiative",
    "nav-partnership": "Partnership",
    "nav-speakers": "Speakers",
    "nav-past-years": "Past Years",
    "nav-snapshot": "THE SnapShot Report",
    "nav-gallery": "Gallery",
    "nav-register": "Register Here",

    // Hero
    "hero-eyebrow": "Canada's Only Tier I Global Mining Investment Conference",
    "hero-title-1": "The",
    "hero-title-2": "Mining",
    "hero-title-3": "Investment",
    "hero-title-4": "Event",
    "hero-subtitle": "Meet investors, discover projects, secure partnerships and shape the future of mining.",
    "hero-date": "1-3 JUNE 2027 · QUÉBEC CITY, CANADA",
    "hero-register": "REGISTER NOW",
    "hero-program": "VIEW PROGRAM",

    // Quick Links
    "ql-sponsors": "Sponsors",
    "ql-companies": "Participating Companies",
    "ql-mining-week": "International Mining Week",
    "ql-agenda": "Agenda",
    "ql-brochure": "Brochure",
    "ql-meet-team": "Speakers",

    // Stats & Glimpse
    "welcome-tag": "WELCOME",
    "glimpse-title": "A Glimpse Inside THE Event",
    "glimpse-desc": "Step inside Canada's only Tier 1 global mining investment conference — where senior producers, emerging developers, institutional capital and the next generation of industry leaders converge under one roof.",
    "discover-event": "DISCOVER THE EVENT",
    "stat-years-label": "YEARS",
    "stat-years-sub": "of Excellence",
    "stat-investors-label": "INVESTORS",
    "stat-investors-sub": "Attending",
    "stat-mining-label": "MINING COMPANIES",
    "stat-mining-sub": "Participating",
    "stat-countries-label": "COUNTRIES",
    "stat-countries-sub": "Represented",
    "stat-meetings-label": "MEETINGS",
    "stat-meetings-sub": "Held",

    // Why Attend
    "why-tag": "WHY ATTEND",
    "why-title": "Your Pathway To Investment Success",
    "why-01-title": "MEET INVESTORS",
    "why-01-desc": "Connect with global investors actively seeking high-potential mining opportunities.",
    "why-02-title": "DISCOVER OPPORTUNITIES",
    "why-02-desc": "Explore high-potential mining projects from around the world.",
    "why-03-title": "BUILD PARTNERSHIPS",
    "why-03-desc": "Create strategic partnerships that drive long-term growth.",
    "why-04-title": "RAISE CAPITAL",
    "why-04-desc": "Secure the capital you need to advance your projects.",

    // Featured Programs Grid
    "programs-tag": "FEATURED INITIATIVES",
    "programs-title": "Key Event Programs",
    "prog-edu-cat": "EDUCATION",
    "prog-edu-title": "Student Sponsorship Program",
    "prog-edu-desc": "Offering a one-of-a-kind exposure to the mining industry for up to 50 university and college students passionate about geology, finance and engineering.",
    "prog-edu-cta": "EXPLORE PROGRAM",
    "prog-lead-cat": "LEADERSHIP",
    "prog-lead-title": "SHE-Co Initiative",
    "prog-lead-desc": "Fostering industry-wide progress through ESG innovation and diversity, highlighting the achievements of women in the global mining sector.",
    "prog-lead-cta": "LEARN MORE",
    "prog-inst-cat": "INSTITUTIONAL",
    "prog-inst-title": "Tier 1 Partnership",
    "prog-inst-desc": "Tailored opportunities designed to maximize visibility and engagement with the world's most influential mining companies and investors.",
    "prog-inst-cta": "PARTNERSHIP INFO",
    "prog-dial-cat": "DIALOGUE",
    "prog-dial-title": "THE Salon Explore Co Lounge",
    "prog-dial-desc": "An intimate networking experience designed to connect Canada's exploration community with elite international investors.",
    "prog-dial-cta": "MEET SPEAKERS",

    // Featured Event Countdown
    "feat-event-tag": "FEATURED EVENT",
    "feat-event-title": "THE MINING INVESTMENT EVENT",
    "feat-event-date": "1-3 JUNE 2027",
    "feat-event-loc": "QUÉBEC CITY, CANADA",
    "feat-event-agenda": "VIEW AGENDA",
    "timer-days": "DAYS",
    "timer-hrs": "HRS",
    "timer-min": "MIN",
    "timer-sec": "SEC",

    // Featured Partners
    "partners-tag": "FEATURED",
    "partners-title": "Featured Partners",
    "partners-sub": "A spotlight on the partners powering THE Mining Investment Event. Switch tiers to explore each circle of supporters.",

    // Canada Premier Forum
    "forum-tag": "THE CONFERENCE",
    "forum-title": "Canada's Premier Mining Forum",
    "forum-desc": "THE Mining Investment Event is an invitation-only gathering that brings together the world's most influential mining companies, investors, institutions and government authorities in the historic setting of Québec City.",
    "forum-highlight": "Independently sponsored by the Government of Québec and the financial and mining communities at large.",
    "forum-bullet-1": "Privately arranged 1-on-1 meetings between mining companies and international investors",
    "forum-bullet-2": "Keynote speakers and industry thought leaders from across the globe",
    "forum-bullet-3": "Promoting sustainability via the Student Sponsorship and SHE-Co initiatives",
    "forum-bullet-4": "Platform for ESG innovation and equality in the mining sector",
    "forum-bullet-5": "Accredited investors, family offices, institutions and sovereign funds",
    "forum-about-btn": "ABOUT THE EVENT",

    // Global Community Map
    "map-tag": "GLOBAL PRESENCE",
    "map-title": "Where the World's Mining Converges",
    "map-desc": "Explore the international network of companies, investors, and delegations gathering in Québec City.",
    "map-cta": "VIEW GLOBAL PARTICIPATION",
    "stat-participants": "PARTICIPANTS",
    "stat-student-sponsors": "STUDENT SPONSORS",
    "stat-program-label": "PROGRAM",

    // Event Highlights & Media
    "highlights-tag": "MEDIA & HIGHLIGHTS",
    "highlights-title": "Event Highlights",
    "highlights-desc": "Three days in Québec City — plenary sessions, privately arranged meetings and the evening programme, captured as they happened.",
    "stat-photos": "PHOTOS",
    "stat-press": "PRESS",
    "media-badge-speeches": "KEYNOTE SPEECHES",
    "media-title-1": "Plenary Keynotes & Strategic Insights",
    "media-desc-1": "Watch executive keynotes from global mining leaders presenting capital strategies.",
    "media-watch": "WATCH REPLAYS",
    "media-badge-interviews": "INTERVIEWS",
    "media-title-2": "C-Suite & Investor Interviews",
    "media-desc-2": "Exclusive 1-on-1 interviews with CEOs, exploration managers, and institutional funds.",
    "media-title-3": "High-Resolution Photo Gallery",
    "media-desc-3": "Explore official photography capturing networking receptions, lounge sessions, and speeches.",
    "media-view-gallery": "VIEW GALLERY",

    // Get In Touch CTA
    "cta-tag": "HAVE A QUESTION?",
    "cta-title": "Get in Touch",
    "cta-desc-prefix": "For more information about 'THE Event' programming or registration, please contact",
    "cta-desc-or": "or call",

    // Footer
    "footer-questions": "WANT TO JOIN WITH US?",
    "footer-initiatives": "INITIATIVES",
    "footer-about": "ABOUT",
    "footer-program": "PROGRAM",
    "footer-disclaimer": "DISCLAIMER",
    "footer-link-student-sponsor": "Student Sponsorship",
    "footer-link-sheco": "SHE-CO",
    "footer-link-student-volunteer": "Student Volunteer",
    "footer-link-registration": "Registration Information",
    "footer-link-our-sponsors": "Our Sponsors",
    "footer-follow-us": "FOLLOW US",
    "footer-disclaimer-text": "This website, the events, information and materials pertaining to and associated with THE Mining Investment Event, are not and should not be construed as an offer to buy or sell, or as a solicitation of an offer to buy or sell, sponsor, advocate, endorse, promote or be construed as making any recommendation or providing investment or other advice for any regulated products, securities or investments.",

    // Navbar dropdown descriptions
    "nav-about-event-desc": "Learn about Canada's premier mining conference",
    "nav-team-desc": "Meet the people behind THE Event",
    "nav-travel-desc": "Venue, hotels and travel information",
    "nav-media-desc": "Latest media coverage and press",
    "nav-newsflash-desc": "Newsletter and industry updates",

    // About page
    "about-breadcrumb-event": "About THE Event",
    "about-hero-title-1": "About",
    "about-hero-title-2": "THE Event",
    "about-lead": "THE Mining Investment EVENT is Canada's Only Tier I Global Mining Investment Conference, held annually in Québec City, Canada.",
    "about-body-1": "THE Event hosts over 100 participating mining companies, is invitation only and is independently sponsored by the Government of Québec, and financial and mining communities at large. It is designed to specifically facilitate privately arranged meetings between mining companies, international investors, and various mining government authorities.",
    "about-body-2": "is committed to promoting sustainability in the mining industry via education and innovation through its unique Student Sponsorship and SHE-Co Initiatives, highlighting ESG and equality issues, and providing a platform for some of the most influential thought leaders in the sector.",
    "about-highlight": "Independently sponsored by the Government of Québec, and the financial and mining communities at large.",
    "about-hl1": "Privately arranged 1-on-1 meetings between mining companies and international investors",
    "about-hl2": "Keynote speakers and industry thought leaders from across the globe",
    "about-hl3": "Promoting sustainability via the Student Sponsorship and SHE-Co Initiatives",
    "about-hl4": "Platform for ESG innovation and equality in the mining sector",
    "about-hl5": "Accredited investors, family offices, institutions, and sovereign funds",
    "about-figure-label": "Québec City · Est. Annual",
    "about-figure-caption": "Privately arranged meetings between mining companies, international investors and government authorities.",
    "about-cta-team": "Meet THE Team",
    "about-quick-facts": "Quick Facts",
    "about-contact-title": "Contact",
    "about-contact-body": "For more information about 'THE Event' programming or registration, please contact",
    "about-contact-or": "or call",
    "about-diff-tag": "WHY THE EVENT",
    "about-diff-title": "What Makes Us Different",
    "about-feat1-title": "Tier I Investment Conference",
    "about-feat1-desc": "An invitation-only gathering independently sponsored by the Government of Québec, bringing together the world's most influential mining companies and investors.",
    "about-feat2-title": "Private 1-on-1 Meetings",
    "about-feat2-desc": "Privately arranged meetings between mining companies, international investors, and various mining government authorities — curated well before doors open.",
    "about-feat3-title": "ESG & Sustainability",
    "about-feat3-desc": "Committed to promoting sustainability via the Student Sponsorship and SHE-Co Initiatives, highlighting ESG innovation and equality in the mining sector.",
    "stat-companies": "Mining Companies",
    "stat-days": "Days of Programming",

    // Team page
    "team-hero-title-1": "THE",
    "team-hero-title-2": "Team",
    "team-core-label": "CORE TEAM",
    "team-core-title-1": "The People Behind",
    "team-core-title-2": "THE Event",
    "team-advisory-label": "ADVISORY BOARD MEMBERS",
    "team-advisory-title": "Advisory Board",
    "team-read-more": "Read More ↓",
    "team-read-less": "Read Less ↑",

    // Travel page
    "travel-hero-title-1": "Travel &",
    "travel-hero-title-2": "Accommodations",
    "travel-venue-label": "VENUE",
    "travel-venue-title-1": "Welcome to",
    "travel-venue-title-2": "Québec City",
    "travel-venue-desc": "Welcome to THE Mining Investment EVENT, taking place 1-3 June 2027 at the Centre des congrès de Québec (\u201cQCC\u201d). Discounted block rates available for registered participants only. You are responsible for coordinating all your own travel and lodging arrangements.",
    "travel-convention-title": "Québec City Convention Centre",
    "travel-convention-desc": "Welcome to the Quebec City Convention Centre, where elegance meets innovation. Nestled within the charming historic district of Old Quebec, this world-class facility seamlessly blends modern amenities with the rich tapestry of Quebecois culture.",
    "travel-convention-note": "Please Note: Entry into THE Event and special hotel discount rates are restricted to registered participants only.",
    "travel-convention-link": "View Convention Centre ↗",
    "travel-air-title": "Air Travel to Quebec (YQB)",
    "travel-air-easy": "Traveling to Quebec City is easy!",
    "travel-air-times": "Estimated flight times:",
    "travel-air-desc": "All major carriers fly to Toronto or Montreal with quick connections to YQB. Jean Lesage International airport is a 20 minute taxi ride to/from the Chateau Frontenac.",
    "travel-air-link": "View YQB Destinations ↗",
    "travel-services-label": "SERVICES",
    "travel-services-title": "Accommodations & Transport",
    "travel-hilton-title": "Hilton Québec",
    "travel-hilton-desc": "Experience luxury and convenience at the Hilton Hotel in Quebec City, perfectly positioned just steps away from the Quebec City Convention Centre. Indulge in exquisite dining, unwind with a cocktail at the lounge, or rejuvenate in the state-of-the-art fitness centre.",
    "travel-hilton-note": "Entry into THE Event and special hotel discount rates are restricted to registered participants only.",
    "travel-hilton-link": "View Hotel Website ↗",
    "travel-train-title": "Train Travel (VIA Rail)",
    "travel-train-desc": "Estimated train times to Quebec City:\n• From Toronto: 8 hrs (transfer at Montreal)\n• From Montreal: 3 hrs\n\nThe train station in Quebec City is just 5 minutes by taxi to most major hotels. Book your tickets online at VIA Rail.",
    "travel-train-link": "Book Train Ticket ↗",
    "travel-limo-title": "Limousine A1",
    "travel-limo-desc": "With over 40 years of experience in transportation management and coordination, Limousine A1 is the leading limousine carrier in the province of Quebec. Their team of professionals provides a personalized transportation experience, seamless logistics, and a courteous attitude.\n\nTel: 418-523-5059\nEmail: res@limousinequebec.com",
    "travel-limo-note": "Entry into THE Event and special discount rates are restricted to registered participants only.",
    "travel-limo-link": "View Limousine A1 ↗",
    "travel-discount-title": "Delegate Discount Program",
    "travel-discount-desc": "Our venue partner, The Québec City Convention Centre, is proud to offer delegates of THE Event exclusive offers and discounts at select restaurants, attractions and boutiques throughout Quebec City.\n\nYou will be able to take advantage of the offers through presentation of your THE Event badge. Scan QR code on-site for more details.",

    // Media page
    "media-hero-title-1": "Recent",
    "media-hero-title-2": "Media",
    "media-gallery-label": "Gallery & Media",
    "media-gallery-title-1": "THE Event in",
    "media-gallery-title-2": "Pictures & Press",
    "media-gallery-desc": "Explore recent coverage, photography, and media from THE Mining Investment Event. For media inquiries and press accreditation, please contact our team directly.",
    "media-tile-conference-floor": "Conference Floor",
    "media-tile-keynote-speakers": "Keynote Speakers",
    "media-tile-networking-events": "Networking Events",
    "media-tile-student-program": "Student Program Gallery",
    "media-tile-sheco-events": "SHE-CO Events",
    "media-tile-conference-sessions": "Conference Sessions",
    "media-tile-panel-discussions": "Panel Discussions",
    "media-tile-industry-leaders": "Industry Leaders",
    "media-tile-welcome-reception": "Welcome Reception",
    "media-tile-event-highlights": "THE Event Highlights",
    "media-tile-investor-meetings": "Investor Meetings",
    "media-tile-award-ceremony": "Award Ceremony",
    "media-tile-quebec-experience": "Quebec City Experience",
    "media-tile-speakers-panels": "Speakers & Panels",
    "media-tile-behind-event": "Behind THE Event",
    "media-tile-exhibitor-showcase": "Exhibitor Showcase",
    "media-tile-networking-dinner": "Networking Dinner",
    "media-tile-event-memories": "THE Event Memories",
    "media-videos-label": "Recent Videos",
    "media-videos-title-1": "Watch THE Event",
    "media-videos-title-2": "in Motion",
    "media-bottom-text": "For full media gallery access, recent press coverage, and media accreditation inquiries:",
    "media-bottom-cta": "Contact for Media Access",

    // Newsflash page
    "news-hero-title-1": "THE",
    "news-hero-title-2": "Newsflash",
    "news-latest-label": "LATEST UPDATES",
    "news-section-title-1": "Stay Informed with",
    "news-section-title-2": "THE Newsflash",
    "news-section-desc": "The latest news, announcements and updates from THE Mining Investment Event. Subscribe to stay current with conference programming, speaker announcements, and initiative updates.",
    "news-read-more": "Read More",
    "news-subscribe-text": "For more information and to subscribe to THE Newsflash, contact",
    "news-filter-all": "All",

    // Student Sponsorship Page
    "student-breadcrumb-init": "Initiatives",
    "student-breadcrumb-prog": "Student Sponsorship Program",
    "student-hero-title-1": "THE Student",
    "student-hero-title-2": "Sponsorship Program",
    "student-tag-label": "BECOME THE FUTURE OF MINING",
    "student-main-subtitle": "Apply now for THE Glencore Student Sponsorship Class of 2026",
    "student-body-p1": "THE Glencore Student Sponsorship Program aims to offer a one-of-a-kind exposure to the mining industry through participation in THE Mining Investment Event (THE Event), Canada's only Tier 1 global mining investment conference, held from June 1–3, 2027, in Quebec City. This annual event serves as a nexus for industry leaders and investors, providing a platform for knowledge exchange, networking, and immersive learning. The Program is now recognized as one of the largest fully funded conference programs in Canada.",
    "student-body-p2": "Up to 50 university or college students with a passion for geology, finance, engineering, or related fields will have the chance to attend the conference at no cost. Our goal is to foster experiential learning by exposing students to keynote speakers, industry panels, professional meet-and-greets, a case study competition, and various networking events. Through these avenues, we hope to instill a sense of global interconnectedness within the Canadian mining industry while investing in the development of the next generation of talented individuals.",
    "student-cta-apply": "Apply Here",
    "student-cta-letter": "Letter from our CEO ↗",
    "student-awards-label": "2025 Award Recipients",
    "student-awards-title-1": "THE Glencore Student Sponsorship",
    "student-awards-title-2": "Program 2025 Award Recipients",
    "student-mvp-label": "MVP — Selected by the Students",
    "student-winning-team-label": "Winning Team — Team 9",
    "student-outstanding-label": "Outstanding Students",
    "student-contact-title": "Contact Information",
    "student-contact-desc": "For more information, please contact Sydney Schuch, Manager of Production Services, IR.INC & VID Media Inc. —",
    "student-closing-note": "We thank all of our students, past and present, who have attended our program. Applications for the Class of 2026 will commence in November 2025. We look forward to hosting the new class of 2026 in beautiful Quebec City.",
    "stat-sponsored-label": "SPONSORED",
    "stat-sponsored-sub": "Fully Funded Students",

    // SHE-CO Page
    "sheco-breadcrumb-init": "Initiatives",
    "sheco-breadcrumb-title": "SHE-CO Initiative",
    "sheco-hero-title-1": "SHE-CO",
    "sheco-hero-title-2": "Initiative",
    "sheco-label": "CHARITABLE INITIATIVE",
    "sheco-title-1": "Empowering Individuals",
    "sheco-title-2": "and Communities",
    "sheco-sub": "Supporting Worthy Educational, Health and Wellness Projects. IR.INC & VID Media's Charitable Initiative.",
    "sheco-body": "Each year a portion of THE Event proceeds are donated to qualified non-profit and charitable groups. Donations will be focused on support to individuals, groups, institutions and/or community projects making a positive difference in the lives of people.",
    "sheco-donations-label": "ANNUAL DONATIONS",
    "sheco-donations-title": "Impact Across Communities",
    "sheco-drum-spotlight": "SPOTLIGHT PROJECT",
    "sheco-drum-title": "THE Drum Circle",
    "sheco-artist-label": "THE RESIDENT ARTIST 2024",
    "sheco-artist-title": "Meet Bertram Turmel",
    "sheco-artist-cta": "Read More About Bertram ↗",

    // Partnership Page
    "tier1-breadcrumb": "Tier 1 Conference Partnership",
    "tier1-h1-1": "Tier 1 Conference",
    "tier1-h1-2": "Partnership",
    "tier1-title-1": "Align Your Brand with",
    "tier1-title-2": "Canada's Premier",
    "tier1-title-3": "Mining Conference",
    "tier1-sub-desc": "Becoming a Tier 1 Conference Partner provides unrivalled access to decision-makers, investors, and influencers across the global mining industry. Our partnerships are tailored to maximize visibility and engagement throughout THE Event.",
    "tier1-cta-pdf": "Download Sponsor PDF ↗",
    "tier1-cta-contact": "Contact Jennifer Choi",
    "tier1-sidebar-tag": "SPONSORSHIP INQUIRY",
    "tier1-sidebar-title": "Contact For Sponsorship",
    "tier1-sidebar-body": "To discuss partnership opportunities, please contact Jennifer Choi directly:",
    "tier1-f1-title": "Brand Visibility",
    "tier1-f1-desc": "Premium logo placement across all THE Event materials, digital platforms, and on-site signage. Your brand reaches 800+ industry leaders, investors, and government representatives.",
    "tier1-f2-title": "Networking Access",
    "tier1-f2-desc": "Exclusive access to private networking events, VIP receptions, and curated 1-on-1 meeting opportunities with mining company executives and international investors.",
    "tier1-f3-title": "Speaking Opportunities",
    "tier1-f3-desc": "Keynote and panel session opportunities provide a powerful platform to position your firm as a thought leader in the global mining investment space.",
    "tier1-f4-title": "ESG Alignment",
    "tier1-f4-desc": "Demonstrate commitment to sustainability and diversity by co-sponsoring THE Event's Student Sponsorship and SHE-Co charitable initiatives.",

    // Speakers Page
    "speakers-hero-title-1": "Keynote",
    "speakers-hero-title-2": "Speakers",
    "speakers-label": "THOUGHT LEADERSHIP",
    "speakers-title": "World-Class Keynotes & Panel Discussions",
    "speakers-sub": "Bringing together government ministers, institutional fund managers, CEOs, and global mining leaders to shape capital allocation and sustainability in the sector.",
    "speakers-inquire-title": "Interested in Speaking Opportunities?",
    "speakers-inquire-desc": "Speaking slots at THE Event provide unrivalled visibility before accredited investors and industry leaders.",
    "speakers-inquire-btn": "Inquire About Speaking Slots",
  },
  FR: {
    // Nav
    "nav-home": "Accueil",
    "nav-about": "À Propos",
    "nav-about-event": "À Propos de L'Événement",
    "nav-team": "L'Équipe",
    "nav-travel": "Voyage et Hébergement",
    "nav-media": "Médias Récents",
    "nav-newsflash": "THE Newsflash",
    "nav-programs": "Programmes",
    "nav-student": "Programme de Bourses Étudiantes",
    "nav-sheco": "Initiative SHE-Co",
    "nav-partnership": "Partenariat",
    "nav-speakers": "Conférenciers",
    "nav-past-years": "Années Précédentes",
    "nav-snapshot": "Rapport SnapShot",
    "nav-gallery": "Galerie",
    "nav-register": "Inscrivez-vous",

    // Hero
    "hero-eyebrow": "La Seule Conférence d'Investissement Minier de Niveau I au Canada",
    "hero-title-1": "L'Événement",
    "hero-title-2": "d'Investissement",
    "hero-title-3": "Minier",
    "hero-title-4": "",
    "hero-subtitle": "Rencontrer des investisseurs, découvrir des projets, sécuriser des partenariats et façonner l'avenir minier.",
    "hero-date": "1-3 JUIN 2027 · VILLE DE QUÉBEC, CANADA",
    "hero-register": "S'INSCRIRE MAINTENANT",
    "hero-program": "VOIR LE PROGRAMME",

    // Quick Links
    "ql-sponsors": "Commanditaires",
    "ql-companies": "Compagnies Participantes",
    "ql-mining-week": "Semaine Internationale des Mines",
    "ql-agenda": "Ordre du Jour",
    "ql-brochure": "Brochure",
    "ql-meet-team": "Conférenciers",

    // Stats & Glimpse
    "welcome-tag": "BIENVENUE",
    "glimpse-title": "Un Aperçu de L'Événement",
    "glimpse-desc": "Découvrez la seule conférence d'investissement minier de niveau 1 au Canada — où producteurs chevronnés, développeurs émergents, capital institutionnel et leaders de demain se réunissent.",
    "discover-event": "DÉCOUVRIR L'ÉVÉNEMENT",
    "stat-years-label": "ANNÉES",
    "stat-years-sub": "d'Excellence",
    "stat-investors-label": "INVESTISSEURS",
    "stat-investors-sub": "Présents",
    "stat-mining-label": "SOCIÉTÉS MINIÈRES",
    "stat-mining-sub": "Participantes",
    "stat-countries-label": "PAYS",
    "stat-countries-sub": "Représentés",
    "stat-meetings-label": "RÉUNIONS",
    "stat-meetings-sub": "Tenues",

    // Why Attend
    "why-tag": "POURQUOI PARTICIPER",
    "why-title": "Votre Voie Vers Le Succès D'Investissement",
    "why-01-title": "RENCONTRER DES INVESTISSEURS",
    "why-01-desc": "Connectez-vous avec des investisseurs mondiaux recherchant des opportunités minières à fort potentiel.",
    "why-02-title": "DÉCOUVRIR DES OPPORTUNITÉS",
    "why-02-desc": "Explorez des projets miniers à fort potentiel à travers le monde.",
    "why-03-title": "BÂTIR DES PARTENARIATS",
    "why-03-desc": "Créez des partenariats stratégiques pour stimuler une croissance à long terme.",
    "why-04-title": "LEVER DU CAPITAL",
    "why-04-desc": "Obtenez le capital nécessaire pour faire avancer vos projets.",

    // Featured Programs Grid
    "programs-tag": "INITIATIVES EN VEDETTE",
    "programs-title": "Programmes Principaux",
    "prog-edu-cat": "ÉDUCATION",
    "prog-edu-title": "Programme de Bourses Étudiantes",
    "prog-edu-desc": "Offrant une exposition unique à l'industrie minière pour jusqu'à 50 étudiants universitaires passionnés par la géologie et la finance.",
    "prog-edu-cta": "EXPLORER LE PROGRAMME",
    "prog-lead-cat": "LEADERSHIP",
    "prog-lead-title": "Initiative SHE-Co",
    "prog-lead-desc": "Favoriser le progrès de l'industrie grâce à l'innovation ESG et à la diversité des femmes dans le secteur minier.",
    "prog-lead-cta": "EN SAVOIR PLUS",
    "prog-inst-cat": "INSTITUTIONNEL",
    "prog-inst-title": "Partenariat de Niveau 1",
    "prog-inst-desc": "Opportunités sur mesure conçues pour maximiser la visibilité auprès des sociétés minières et investisseurs influents.",
    "prog-inst-cta": "INFO PARTENARIAT",
    "prog-dial-cat": "DIALOGUE",
    "prog-dial-title": "Le Salon ExplorCo Lounge",
    "prog-dial-desc": "Une expérience de réseautage intime pour connecter la communauté d'exploration du Canada aux investisseurs mondiaux.",
    "prog-dial-cta": "RENCONTRER LES CONFÉRENCIERS",

    // Featured Event Countdown
    "feat-event-tag": "ÉVÉNEMENT EN VEDETTE",
    "feat-event-title": "L'ÉVÉNEMENT D'INVESTISSEMENT MINIER",
    "feat-event-date": "1-3 JUIN 2027",
    "feat-event-loc": "VILLE DE QUÉBEC, CANADA",
    "feat-event-agenda": "VOIR L'ORDRE DU JOUR",
    "timer-days": "JOURS",
    "timer-hrs": "HRS",
    "timer-min": "MIN",
    "timer-sec": "SEC",

    // Featured Partners
    "partners-tag": "EN VEDETTE",
    "partners-title": "Partenaires en Vedette",
    "partners-sub": "Un coup de projecteur sur les partenaires propulsant L'Événement d'Investissement Minier. Changez de niveau pour explorer chaque cercle de supporters.",

    // Canada Premier Forum
    "forum-tag": "LA CONFÉRENCE",
    "forum-title": "Premier Forum Minier du Canada",
    "forum-desc": "L'Événement d'Investissement Minier est un rassemblement sur invitation réunissant les sociétés minières et investisseurs les plus influents au monde dans le cadre historique de la ville de Québec.",
    "forum-highlight": "Parrainé indépendamment par le gouvernement du Québec ainsi que la communauté financière et minière dans son ensemble.",
    "forum-bullet-1": "Rencontres privées 1 à 1 organisées entre sociétés minières et investisseurs internationaux",
    "forum-bullet-2": "Conférenciers principaux et leaders d'opinion de l'industrie venus du monde entier",
    "forum-bullet-3": "Promotion de la durabilité via les initiatives de Bourses Étudiantes et SHE-Co",
    "forum-bullet-4": "Plateforme d'innovation ESG et d'égalité dans le secteur minier",
    "forum-bullet-5": "Investisseurs accrédités, bureaux de gestion de patrimoine, institutions et fonds souverains",
    "forum-about-btn": "À PROPOS DE L'ÉVÉNEMENT",

    // Global Community Map
    "map-tag": "PRÉSENCE MONDIALE",
    "map-title": "Où le Monde Minier Converge",
    "map-desc": "Explorez le réseau international d'entreprises, d'investisseurs et de délégations réunies à Québec.",
    "map-cta": "VOIR LA PARTICIPATION MONDIALE",
    "stat-participants": "PARTICIPANTS",
    "stat-student-sponsors": "BOURSES ÉTUDIANTES",
    "stat-program-label": "PROGRAMME",

    // Event Highlights & Media
    "highlights-tag": "MÉDIAS ET FAITS SAILLANTS",
    "highlights-title": "Faits Saillants de l'Événement",
    "highlights-desc": "Trois jours à Québec — sessions plénières, réunions privées et programme de soirée capturés en direct.",
    "stat-photos": "PHOTOS",
    "stat-press": "PRESSE",
    "media-badge-speeches": "DISCOURS PRINCIPAUX",
    "media-title-1": "Conférences Plénières et Perspectives Stratégiques",
    "media-desc-1": "Regardez les discours des leaders miniers mondiaux présentant leurs stratégies de capital.",
    "media-watch": "REGARDER LES REDIFFUSIONS",
    "media-badge-interviews": "ENTREVUES",
    "media-title-2": "Entrevues Exécutives & Investisseurs",
    "media-desc-2": "Entrevues exclusives 1 à 1 avec les PDG, directeurs d'exploration et fonds institutionnels.",
    "media-title-3": "Galerie Photos Haute Résolution",
    "media-desc-3": "Explorez la photographie officielle capturant les réceptions de réseautage et conférences.",
    "media-view-gallery": "VOIR LA GALERIE",

    // Get In Touch CTA
    "cta-tag": "UNE QUESTION ?",
    "cta-title": "Contactez-Nous",
    "cta-desc-prefix": "Pour plus d'informations sur le programme de 'L'Événement' ou l'inscription, veuillez contacter",
    "cta-desc-or": "ou appeler le",

    // Footer
    "footer-questions": "VOUS SOUHAITEZ VOUS JOINDRE À NOUS ?",
    "footer-initiatives": "INITIATIVES",
    "footer-about": "À PROPOS",
    "footer-program": "PROGRAMME",
    "footer-disclaimer": "AVIS DE NON-RESPONSABILITÉ",
    "footer-link-student-sponsor": "Bourses Étudiantes",
    "footer-link-sheco": "SHE-CO",
    "footer-link-student-volunteer": "Bénévoles Étudiants",
    "footer-link-registration": "Informations d'Inscription",
    "footer-link-our-sponsors": "Nos Commanditaires",
    "footer-follow-us": "SUIVEZ-NOUS",
    "footer-disclaimer-text": "Ce site Web, les événements, les informations et les documents relatifs à L'Événement d'Investissement Minier ne constituent pas et ne doivent pas être interprétés comme une offre d'achat ou de vente.",

    // Navbar dropdown descriptions
    "nav-about-event-desc": "En savoir plus sur la première conférence minière du Canada",
    "nav-team-desc": "Rencontrez les personnes derrière L'Événement",
    "nav-travel-desc": "Lieu, hôtels et informations de voyage",
    "nav-media-desc": "Dernière couverture médiatique et presse",
    "nav-newsflash-desc": "Bulletin d'information et actualités de l'industrie",

    // About page
    "about-breadcrumb-event": "À Propos de L'Événement",
    "about-hero-title-1": "À Propos de",
    "about-hero-title-2": "L'Événement",
    "about-lead": "L'Événement d'Investissement Minier est la seule conférence mondiale de niveau I sur l'investissement minier au Canada, tenue annuellement à Québec, Canada.",
    "about-body-1": "L'Événement accueille plus de 100 sociétés minières participantes, est sur invitation uniquement et est parrainé indépendamment par le gouvernement du Québec, ainsi que par les communautés financières et minières. Il est conçu pour faciliter les réunions privées entre les sociétés minières, les investisseurs internationaux et les autorités gouvernementales.",
    "about-body-2": "s'engage à promouvoir la durabilité dans l'industrie minière via l'éducation et l'innovation à travers ses initiatives uniques de Bourses Étudiantes et SHE-Co, mettant en lumière les enjeux ESG et d'égalité.",
    "about-highlight": "Parrainé indépendamment par le gouvernement du Québec et les communautés financières et minières dans leur ensemble.",
    "about-hl1": "Rencontres privées 1 à 1 organisées entre sociétés minières et investisseurs internationaux",
    "about-hl2": "Conférenciers principaux et leaders d'opinion de l'industrie venus du monde entier",
    "about-hl3": "Promotion de la durabilité via les initiatives de Bourses Étudiantes et SHE-Co",
    "about-hl4": "Plateforme d'innovation ESG et d'égalité dans le secteur minier",
    "about-hl5": "Investisseurs accrédités, bureaux de gestion de patrimoine, institutions et fonds souverains",
    "about-figure-label": "Québec · Annuel",
    "about-figure-caption": "Réunions privées entre sociétés minières, investisseurs internationaux et autorités gouvernementales.",
    "about-cta-team": "Rencontrer L'Équipe",
    "about-quick-facts": "Faits Rapides",
    "about-contact-title": "Contact",
    "about-contact-body": "Pour plus d'informations sur le programme de 'L'Événement' ou l'inscription, veuillez contacter",
    "about-contact-or": "ou appeler le",
    "about-diff-tag": "POURQUOI L'ÉVÉNEMENT",
    "about-diff-title": "Ce Qui Nous Distingue",
    "about-feat1-title": "Conférence d'Investissement de Niveau I",
    "about-feat1-desc": "Un rassemblement sur invitation uniquement parrainé indépendamment par le gouvernement du Québec, réunissant les sociétés minières et investisseurs les plus influents au monde.",
    "about-feat2-title": "Réunions Privées 1 à 1",
    "about-feat2-desc": "Réunions privées organisées entre sociétés minières, investisseurs internationaux et autorités gouvernementales — préparées bien avant l'ouverture des portes.",
    "about-feat3-title": "ESG et Durabilité",
    "about-feat3-desc": "Engagement à promouvoir la durabilité via les initiatives de Bourses Étudiantes et SHE-Co, mettant en lumière l'innovation ESG et l'égalité dans le secteur minier.",
    "stat-companies": "Sociétés Minières",
    "stat-days": "Jours de Programmation",

    // Team page
    "team-hero-title-1": "L'",
    "team-hero-title-2": "Équipe",
    "team-core-label": "ÉQUIPE PRINCIPALE",
    "team-core-title-1": "Les Personnes Derrière",
    "team-core-title-2": "L'Événement",
    "team-advisory-label": "MEMBRES DU CONSEIL CONSULTATIF",
    "team-advisory-title": "Conseil Consultatif",
    "team-read-more": "Lire Plus ↓",
    "team-read-less": "Lire Moins ↑",

    // Travel page
    "travel-hero-title-1": "Voyage et",
    "travel-hero-title-2": "Hébergement",
    "travel-venue-label": "LIEU",
    "travel-venue-title-1": "Bienvenue à",
    "travel-venue-title-2": "Québec",
    "travel-venue-desc": "Bienvenue à L'ÉVÉNEMENT d'Investissement Minier, qui se tiendra du 1 au 3 juin 2027 au Centre des congrès de Québec (\u00abCCQ\u00bb). Tarifs de groupe réduits offerts aux participants inscrits seulement. Vous êtes responsable de la coordination de tous vos arrangements de voyage et d'hébergement.",
    "travel-convention-title": "Centre des Congrès de Québec",
    "travel-convention-desc": "Bienvenue au Centre des congrès de Québec, où l'élégance rencontre l'innovation. Niché au cœur du charmant quartier historique du Vieux-Québec, cet établissement de classe mondiale allie harmonieusement installations modernes et riche patrimoine québécois.",
    "travel-convention-note": "Veuillez noter : L'accès à L'Événement et les tarifs hôteliers préférentiels sont réservés aux participants inscrits uniquement.",
    "travel-convention-link": "Voir le Centre des Congrès ↗",
    "travel-air-title": "Voyage Aérien vers Québec (YQB)",
    "travel-air-easy": "Voyager à Québec est facile !",
    "travel-air-times": "Temps de vol estimés :",
    "travel-air-desc": "Tous les grands transporteurs aériens desservent Toronto ou Montréal avec des connexions rapides vers YQB. L'aéroport international Jean-Lesage est à 20 minutes en taxi du Château Frontenac.",
    "travel-air-link": "Voir les Destinations YQB ↗",
    "travel-services-label": "SERVICES",
    "travel-services-title": "Hébergement et Transport",
    "travel-hilton-title": "Hilton Québec",
    "travel-hilton-desc": "Vivez le luxe et la commodité à l'Hôtel Hilton de Québec, idéalement situé à quelques pas du Centre des congrès de Québec. Savourez une cuisine exquise, détendez-vous avec un cocktail au salon ou ressourcez-vous dans le centre de conditionnement physique dernier cri.",
    "travel-hilton-note": "L'accès à L'Événement et les tarifs hôteliers préférentiels sont réservés aux participants inscrits uniquement.",
    "travel-hilton-link": "Voir le Site de l'Hôtel ↗",
    "travel-train-title": "Voyage en Train (VIA Rail)",
    "travel-train-desc": "Temps de train estimés vers Québec :\n• De Toronto : 8 h (correspondance à Montréal)\n• De Montréal : 3 h\n\nLa gare de Québec est à seulement 5 minutes en taxi de la plupart des grands hôtels. Réservez vos billets en ligne sur VIA Rail.",
    "travel-train-link": "Réserver un Billet de Train ↗",
    "travel-limo-title": "Limousine A1",
    "travel-limo-desc": "Avec plus de 40 ans d'expérience en gestion et coordination du transport, Limousine A1 est le principal transporteur de limousines de la province de Québec. Leur équipe de professionnels offre une expérience de transport personnalisée, une logistique sans faille et une attitude courtoise.\n\nTél : 418-523-5059\nCourriel : res@limousinequebec.com",
    "travel-limo-note": "L'accès à L'Événement et les tarifs préférentiels sont réservés aux participants inscrits uniquement.",
    "travel-limo-link": "Voir Limousine A1 ↗",
    "travel-discount-title": "Programme de Rabais pour Délégués",
    "travel-discount-desc": "Notre partenaire de site, le Centre des Congrès de Québec, est fier d'offrir aux délégués de L'Événement des offres et des réductions exclusives dans certains restaurants, attractions et boutiques de Québec.\n\nVous pourrez profiter des offres en présentant votre badge L'Événement. Scannez le code QR sur place pour plus de détails.",

    // Media page
    "media-hero-title-1": "Médias",
    "media-hero-title-2": "Récents",
    "media-gallery-label": "Galerie et Médias",
    "media-gallery-title-1": "L'Événement en",
    "media-gallery-title-2": "Images et Presse",
    "media-gallery-desc": "Explorez les couvertures récentes, la photographie et les médias de L'Événement d'Investissement Minier. Pour les demandes médias et l'accréditation presse, veuillez contacter notre équipe directement.",
    "media-tile-conference-floor": "Salle de Conférence",
    "media-tile-keynote-speakers": "Conférenciers Principaux",
    "media-tile-networking-events": "Événements de Réseautage",
    "media-tile-student-program": "Galerie du Programme Étudiant",
    "media-tile-sheco-events": "Événements SHE-CO",
    "media-tile-conference-sessions": "Sessions de Conférence",
    "media-tile-panel-discussions": "Discussions en Panel",
    "media-tile-industry-leaders": "Leaders de l'Industrie",
    "media-tile-welcome-reception": "Réception de Bienvenue",
    "media-tile-event-highlights": "Faits Saillants de L'Événement",
    "media-tile-investor-meetings": "Réunions Investisseurs",
    "media-tile-award-ceremony": "Cérémonie de Remise des Prix",
    "media-tile-quebec-experience": "Expérience de Québec",
    "media-tile-speakers-panels": "Conférenciers et Panels",
    "media-tile-behind-event": "Les Coulisses de L'Événement",
    "media-tile-exhibitor-showcase": "Vitrine des Exposants",
    "media-tile-networking-dinner": "Dîner de Réseautage",
    "media-tile-event-memories": "Souvenirs de L'Événement",
    "media-videos-label": "Vidéos Récentes",
    "media-videos-title-1": "Regarder L'Événement",
    "media-videos-title-2": "en Mouvement",
    "media-bottom-text": "Pour l'accès à la galerie complète, la couverture médiatique récente et les demandes d'accréditation :",
    "media-bottom-cta": "Contacter pour Accès Médias",

    // Newsflash page
    "news-hero-title-1": "THE",
    "news-hero-title-2": "Newsflash",
    "news-latest-label": "DERNIÈRES MISES À JOUR",
    "news-section-title-1": "Restez Informé avec",
    "news-section-title-2": "THE Newsflash",
    "news-section-desc": "Les dernières nouvelles, annonces et mises à jour de L'Événement d'Investissement Minier. Abonnez-vous pour rester au courant de la programmation, des annonces de conférenciers et des mises à jour des initiatives.",
    "news-read-more": "Lire Plus",
    "news-subscribe-text": "Pour plus d'informations et pour vous abonner à THE Newsflash, contactez",
    "news-filter-all": "Tous",

    // Student Sponsorship Page
    "student-breadcrumb-init": "Initiatives",
    "student-breadcrumb-prog": "Programme de Bourses Étudiantes",
    "student-hero-title-1": "Le Programme de",
    "student-hero-title-2": "Bourses Étudiantes",
    "student-tag-label": "DEVENEZ L'AVENIR DE L'INDUSTRIE MINIÈRE",
    "student-main-subtitle": "Postulez dès maintenant pour la promotion 2026 du Programme de Bourses Étudiantes Glencore",
    "student-body-p1": "Le programme de bourses étudiantes Glencore vise à offrir une exposition unique à l'industrie minière grâce à une participation à L'Événement d'Investissement Minier (L'Événement), la seule conférence d'investissement minier mondiale de Niveau 1 au Canada, qui se tiendra du 1er au 3 juin 2027 à Québec. Cet événement annuel sert de point de rencontre pour les leaders de l'industrie et les investisseurs.",
    "student-body-p2": "Jusqu'à 50 étudiants universitaires ou collégiens passionnés de géologie, finance ou génie auront la chance d'assister à la conférence sans aucun coût. Notre objectif est de favoriser l'apprentissage expérientiel en exposant les étudiants aux conférenciers d'honneur et panels de l'industrie.",
    "student-cta-apply": "Postuler ici",
    "student-cta-letter": "Une lettre de notre PDG ↗",
    "student-awards-label": "Lauréats 2025",
    "student-awards-title-1": "Programme de Bourses Étudiantes Glencore",
    "student-awards-title-2": "Récipiendaires des Prix 2025",
    "student-mvp-label": "MVP — Sélectionné par les Étudiants",
    "student-winning-team-label": "Équipe Gagnante — Équipe 9",
    "student-outstanding-label": "Étudiants Remarquables",
    "student-contact-title": "Coordonnées de Contact",
    "student-contact-desc": "Pour plus d'informations, veuillez contacter Sydney Schuch, directrice des services de production, IR.INC & VID Media Inc. —",
    "student-closing-note": "Nous remercions tous nos étudiants, passés et présents. Les candidatures pour la promotion 2026 débuteront en novembre 2025. Nous avons hâte d'accueillir la promotion 2026 à Québec.",
    "stat-sponsored-label": "PARRAINÉS",
    "stat-sponsored-sub": "Étudiants Entièrement Financés",

    // SHE-CO Page
    "sheco-breadcrumb-init": "Initiatives",
    "sheco-breadcrumb-title": "Initiative SHE-CO",
    "sheco-hero-title-1": "Initiative",
    "sheco-hero-title-2": "SHE-CO",
    "sheco-label": "INITIATIVE DE BIENFAISANCE",
    "sheco-title-1": "Autonomiser les Individus",
    "sheco-title-2": "et les Communautés",
    "sheco-sub": "Soutenir des projets d'éducation, de santé et de bien-être. L'initiative caritative d'IR.INC et VID Media.",
    "sheco-body": "Chaque année, une partie des bénéfices de L'Événement est versée à des organismes à but non lucratif et caritatifs qualifiés. Les dons viseront le soutien aux individus, groupes, institutions et projets communautaires apportant un changement positif.",
    "sheco-donations-label": "DONS ANNUELS",
    "sheco-donations-title": "Un Impact au Cœur des Communautés",
    "sheco-drum-spotlight": "PROJET EN VEDETTE",
    "sheco-drum-title": "THE Drum Circle",
    "sheco-artist-label": "L'ARTISTE EN RÉSIDENCE 2024",
    "sheco-artist-title": "Rencontrez Bertram Turmel",
    "sheco-artist-cta": "En savoir plus sur Bertram ↗",

    // Partnership Page
    "tier1-breadcrumb": "Partenariat de Conférence Niveau 1",
    "tier1-h1-1": "Partenariat de",
    "tier1-h1-2": "Conférence Niveau 1",
    "tier1-title-1": "Associez Votre Marque à",
    "tier1-title-2": "la Première Conférence",
    "tier1-title-3": "Minière du Canada",
    "tier1-sub-desc": "Devenir partenaire de Niveau 1 offre un accès inégalé aux décideurs, investisseurs et influenceurs de l'industrie minière mondiale. Nos partenariats sont conçus pour maximiser la visibilité et l'engagement tout au long de L'Événement.",
    "tier1-cta-pdf": "Télécharger le PDF Commanditaires ↗",
    "tier1-cta-contact": "Contacter Jennifer Choi",
    "tier1-sidebar-tag": "DEMANDE DE COMMANDITE",
    "tier1-sidebar-title": "Contact pour Commandite",
    "tier1-sidebar-body": "Pour discuter des opportunités de partenariat, veuillez contacter Jennifer Choi directement :",
    "tier1-f1-title": "Visibilité de la Marque",
    "tier1-f1-desc": "Placement de logo haut de gamme sur tout le matériel de L'Événement, les plateformes numériques et la signalétique sur place. Votre marque touche plus de 800 leaders de l'industrie et investisseurs.",
    "tier1-f2-title": "Accès au Réseautage",
    "tier1-f2-desc": "Accès exclusif aux événements de réseautage privés, réceptions VIP et rencontres individuelles sur mesure avec les dirigeants de sociétés minières.",
    "tier1-f3-title": "Opportunités de Prise de Parole",
    "tier1-f3-desc": "Les opportunités de conférences et de panels offrent une tribune puissante pour positionner votre entreprise comme leader d'opinion.",
    "tier1-f4-title": "Alignement ESG",
    "tier1-f4-desc": "Démontrez votre engagement envers la durabilité et la diversité en coparrainant les bourses étudiantes et l'initiative SHE-Co.",

    // Speakers Page
    "speakers-hero-title-1": "Conférenciers",
    "speakers-hero-title-2": "Principaux",
    "speakers-label": "LEADERSHIP D'OPINION",
    "speakers-title": "Conférenciers et Panels de Classe Mondiale",
    "speakers-sub": "Rassemblement de ministres, gestionnaires de fonds institutionnels, PDG et leaders miniers mondiaux pour façonner l'allocation de capital et la durabilité dans le secteur.",
    "speakers-inquire-title": "Intéressé par les Opportunités de Conférence ?",
    "speakers-inquire-desc": "Les créneaux de présentation à L'Événement offrent une visibilité inégalée devant les investisseurs accrédités et leaders de l'industrie.",
    "speakers-inquire-btn": "Demander un Créneau de Présentation",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>("EN");

  useEffect(() => {
    const saved = localStorage.getItem("preferredLanguage");
    if (saved === "EN" || saved === "FR") {
      setLangState(saved);
    }
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem("preferredLanguage", newLang);
  };

  const t = (key: string, fallback?: string): string => {
    const langDict = translations[lang];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
